In [11]:
import numpy as np
from numpy import *

# Array

In [14]:
arr = array([1,2,3,4,5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [24]:
arr.dtype

dtype('int32')

In [26]:
print(arr)

[1 2 3 4 5]


# Linespace 

In [39]:
arr = linspace(0,10,5)

In [41]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [51]:
arr = linspace(0,100,5)

In [53]:
arr

array([  0.,  25.,  50.,  75., 100.])

In [56]:
arr = linspace(0,100,15)

In [59]:
arr

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

# aRange

In [63]:
arr_list = arange(0,10)

In [66]:
arr_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr_list = arange(0,10,2)

In [70]:
arr_list

array([0, 2, 4, 6, 8])

# Zeros

In [76]:
arr = zeros(10)

In [78]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [93]:
arr = zeros((3,3))

In [95]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [97]:
arr = zeros((3,3),bool)
arr

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# Ones

In [82]:
arr = ones(10)

In [84]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
arr = ones((3,3))

In [90]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
arr = ones((3,3),bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Reshae

In [116]:
arr = arange(1,11)

In [118]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
arr = arr.reshape(2,5)

In [122]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [124]:
arr = arange(1,10)

In [126]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# flatten

In [132]:
arr = arange(1,10).reshape(3,3,)

In [134]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
arr = arr.flatten()

In [146]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
# Transpose

In [155]:
arr = arange(1,11).reshape(2,5)

In [157]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [159]:
arr = arr.transpose()

In [161]:
arr

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [163]:
arr = arange(1,10).reshape(3,3)

In [165]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
arr = arr.transpose()

In [173]:
arr

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Array Slicing 

In [180]:
arr = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [182]:
arr[0][0]

1

In [188]:
arr[:,0:1] # [row,col]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [192]:
arr[0:5,:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [198]:
arr[:,-1:]

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [200]:
arr[-1:,:]

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])